spring.application.name=calTracker

spring.datasource.url=jdbc:postgresql://localhost:5432/caltracker
spring.datasource.username=caltracker_app
spring.datasource.password=caltracker_dev_pw_2026

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
