-- The schema exactly as Hibernate's ddl-auto=update had built it by v2/v3 plus
-- the macros PR. A database that already has this table is baselined at V1
-- (see spring.flyway.baseline-* in application.properties) and skips this file;
-- a fresh database — the test DB, CI, a hosted one — runs it.
CREATE TABLE meal_entries (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calories INTEGER NOT NULL,
    date     DATE,
    name     VARCHAR(255),
    carbs    DOUBLE PRECISION,
    fats     DOUBLE PRECISION,
    protein  DOUBLE PRECISION
);
